/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import pojos.Patient;

/**
 *
 * @author gustavo
 */
public class DoctorMenuInterface extends javax.swing.JFrame {

    /**
     * Creates new form DoctorMenuInterface
     */
    public DoctorMenuInterface() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addpat = new javax.swing.JButton();
        searchbyname = new javax.swing.JButton();
        searchEMG = new javax.swing.JButton();
        searchECG = new javax.swing.JButton();
        searchform = new javax.swing.JButton();
        deletepat = new javax.swing.JButton();
        changeusername = new javax.swing.JButton();
        changepassword = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Hi! Doc");

        addpat.setText("Add Patient");
        addpat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpatActionPerformed(evt);
            }
        });

        searchbyname.setText("Search Patient by Name");

        searchEMG.setText("Search EMG by Name");

        searchECG.setText("Search ECG by Name");

        searchform.setText("Search Form by Name");
        searchform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchformActionPerformed(evt);
            }
        });

        deletepat.setText("Delete Patient");

        changeusername.setText("Change Username");

        changepassword.setText("Change Password");

        back.setText("Go back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchbyname)
                            .addComponent(addpat)
                            .addComponent(searchEMG)
                            .addComponent(searchECG)
                            .addComponent(searchform)
                            .addComponent(deletepat)
                            .addComponent(changeusername)
                            .addComponent(changepassword)
                            .addComponent(back)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1)))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(addpat)
                .addGap(18, 18, 18)
                .addComponent(searchbyname)
                .addGap(18, 18, 18)
                .addComponent(searchEMG)
                .addGap(18, 18, 18)
                .addComponent(searchECG)
                .addGap(18, 18, 18)
                .addComponent(searchform)
                .addGap(18, 18, 18)
                .addComponent(deletepat)
                .addGap(18, 18, 18)
                .addComponent(changeusername)
                .addGap(18, 18, 18)
                .addComponent(changepassword)
                .addGap(18, 18, 18)
                .addComponent(back)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchformActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchformActionPerformed

    private void addpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpatActionPerformed
        // TODO add your handling code here:
        AddPatient addpat = new AddPatient();
        addpat.setVisible(true);
        
        Patient patient;
        
        
    }//GEN-LAST:event_addpatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorMenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorMenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorMenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorMenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorMenuInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton addpat;
    private javax.swing.JButton back;
    private javax.swing.JButton changepassword;
    private javax.swing.JButton changeusername;
    private javax.swing.JButton deletepat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton searchECG;
    private javax.swing.JButton searchEMG;
    private javax.swing.JButton searchbyname;
    private javax.swing.JButton searchform;
    // End of variables declaration//GEN-END:variables
}
